/**
 * Tests for the itmlogic preparatory subroutines (hzns, dlthx, zlsq1).
 *
 * Reference values were generated by the Python itmlogic package (v1.2)
 * installed from PyPI.  Each test case creates the same terrain profile
 * in Float64Array "pfl" format and compares the outputs.
 */

import { describe, it, expect } from 'vitest'
import { hzns, dlthx, zlsq1 } from '@/lib/propagation/itmlogic/preparatory'
// Float64Array is a global — no import needed

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build a terrain-profile array in itmlogic "pfl" format:
 *   index 0 — number of intervals (np)
 *   index 1 — spacing (xi)
 *   index 2 … np+2 — elevation values
 *
 * @param np       Number of intervals (points − 1).
 * @param xi       Spacing between samples (metres).
 * @param elevFn   Function that returns elevation at interval index 0..np.
 * @returns        Float64Array in pfl format.
 */
function makePfl(np: number, xi: number, elevFn: (i: number, frac: number) => number): Float64Array {
  const pfl = new Float64Array(np + 3)
  pfl[0] = np
  pfl[1] = xi
  for (let i = 0; i <= np; i++) {
    pfl[i + 2] = elevFn(i, i / np)
  }
  return pfl
}

/**
 * Constant elevation (flat terrain).
 */
function flatElev(constant: number): (i: number, frac: number) => number {
  return () => constant
}

/**
 * Gaussian hill profile.
 */
function gaussianHill(
  base: number,
  height: number,
  center: number,
  sigma: number,
): (i: number, frac: number) => number {
  return (_i: number, frac: number) =>
    base + height * Math.exp(-((frac - center) ** 2) / (2 * sigma ** 2))
}

/**
 * Linear ramp.
 */
function linearRamp(startElev: number, endElev: number): (i: number, frac: number) => number {
  return (_i: number, frac: number) => startElev + (endElev - startElev) * frac
}

// ---------------------------------------------------------------------------
// Shared constants
// ---------------------------------------------------------------------------

/** Typical effective earth curvature for mid-latitudes. */
const GME = 1.38e-6
const HG: [number, number] = [30, 10]

const DIST_10KM = 10000
const NP_500 = 500
const XI_10KM = DIST_10KM / NP_500

const DIST_1KM = 1000
const NP_50 = 50
const XI_1KM = DIST_1KM / NP_50

// Precision tolerance for floating-point comparisons.
const TOL = 1e-6

// ---------------------------------------------------------------------------
// zlsq1 — linear least-squares fit
// ---------------------------------------------------------------------------

describe('zlsq1', () => {
  it('flat profile returns constant heights', () => {
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    const [z0, zn] = zlsq1(pfl, 0, DIST_10KM)
    expect(z0).toBeCloseTo(100, 6)
    expect(zn).toBeCloseTo(100, 6)
  })

  it('linear ramp returns exact endpoints', () => {
    const pfl = makePfl(NP_500, XI_10KM, linearRamp(100, 300))
    const [z0, zn] = zlsq1(pfl, 0, DIST_10KM)
    // A linear ramp should be perfectly fitted: z0 ≈ 100, zn ≈ 300
    expect(z0).toBeCloseTo(100, 4)
    expect(zn).toBeCloseTo(300, 4)
  })

  it('subset of a linear ramp', () => {
    const pfl = makePfl(NP_500, XI_10KM, linearRamp(100, 500))
    const [z0, zn] = zlsq1(pfl, 2000, 8000)
    // zlsq1 fits the line to the [x1,x2] segment but evaluates at the
    // profile endpoints (0 and xn).  For a perfect linear ramp the
    // extrapolated fit should equal the ramp endpoints.
    expect(z0).toBeCloseTo(100, 2)
    expect(zn).toBeCloseTo(500, 2)
  })

  it('mountain ridge (matches Python reference)', () => {
    // Reference from Python: z0=260.7686, zn=343.3647 (full profile)
    // Build the ridge profile (matches Test 5 from the validation script)
    const pfl = makePfl(NP_500, XI_10KM, (_i, frac) => {
      if (Math.abs(frac - 0.6) < 0.05) return 500
      if (frac < 0.6) return 100 + (frac / 0.6) * 400
      return 500 + ((frac - 0.6) / 0.4) * (-400)
    })
    const [z0, zn] = zlsq1(pfl, 0, DIST_10KM)
    expect(z0).toBeCloseTo(260.7686, 1)
    expect(zn).toBeCloseTo(343.3647, 1)
  })

  it('subset of mountain ridge (matches Python reference)', () => {
    const pfl = makePfl(NP_500, XI_10KM, (_i, frac) => {
      if (Math.abs(frac - 0.6) < 0.05) return 500
      if (frac < 0.6) return 100 + (frac / 0.6) * 400
      return 500 + ((frac - 0.6) / 0.4) * (-400)
    })
    const [z0, zn] = zlsq1(pfl, 2000, 8000)
    // Python: z0=257.9287, zn=504.5158
    expect(z0).toBeCloseTo(257.9287, 1)
    expect(zn).toBeCloseTo(504.5158, 1)
  })

  it('degenerate short segment returns values without crashing', () => {
    // Very short segment — should not crash even with xb <= xa
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    const [z0, zn] = zlsq1(pfl, 0, 1) // tiny segment
    expect(Number.isFinite(z0)).toBe(true)
    expect(Number.isFinite(zn)).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// hzns — horizon parameters
// ---------------------------------------------------------------------------

describe('hzns', () => {
  it('flat terrain — horizon distances equal total path (LOS)', () => {
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    const { the, dl } = hzns(pfl, DIST_10KM, HG, GME)
    // On flat terrain the horizon is never closer than the far end.
    expect(dl[0]).toBeCloseTo(DIST_10KM, 2)
    expect(dl[1]).toBeCloseTo(DIST_10KM, 2)
  })

  it('flat terrain — take-off angles are negative (earth curvature)', () => {
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    const { the } = hzns(pfl, DIST_10KM, HG, GME)
    // Both angles should be negative (below horizontal) due to curvature.
    expect(the[0]).toBeLessThan(0)
    expect(the[1]).toBeLessThan(0)
  })

  it('flat terrain — matches Python reference values', () => {
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    const { the, dl } = hzns(pfl, DIST_10KM, HG, GME)
    // Python: the[0]=-0.0089, the[1]=-0.0049, dl = {0:10000, 1:10000}
    expect(the[0]).toBeCloseTo(-0.0089, 3)
    expect(the[1]).toBeCloseTo(-0.0049, 3)
    expect(dl[0]).toBeCloseTo(10000, 0)
    expect(dl[1]).toBeCloseTo(10000, 0)
  })

  it('single hill — finds closer horizon', () => {
    const pfl = makePfl(NP_500, XI_10KM, gaussianHill(100, 50, 0.5, 0.1))
    const { the, dl } = hzns(pfl, DIST_10KM, HG, GME)
    // The hill at the centre should cause a closer horizon distance.
    expect(dl[0]).toBeLessThan(DIST_10KM)
    expect(dl[1]).toBeLessThan(DIST_10KM)
    // Python: dl[0]=4860, dl[1]=4760
    expect(dl[0]).toBeCloseTo(4860, 0)
    expect(dl[1]).toBeCloseTo(4760, 0)
  })

  it('single hill — take-off angles positive (obstructed)', () => {
    const pfl = makePfl(NP_500, XI_10KM, gaussianHill(100, 50, 0.5, 0.1))
    const { the } = hzns(pfl, DIST_10KM, HG, GME)
    // Obstruction makes the take-off angles positive.
    expect(the[0]).toBeGreaterThan(0)
    expect(the[1]).toBeGreaterThan(0)
    // Python: the[0]=0.000661, the[1]=0.00482
    expect(the[0]).toBeCloseTo(0.000661, 3)
    expect(the[1]).toBeCloseTo(0.00482, 3)
  })

  it('two hills — matches Python reference', () => {
    const pfl = makePfl(NP_500, XI_10KM, (_i, frac) => {
      let elev = 100
      elev += 60 * Math.exp(-((frac - 0.3) ** 2) / (2 * 0.08 ** 2))
      elev += 40 * Math.exp(-((frac - 0.7) ** 2) / (2 * 0.06 ** 2))
      return elev
    })
    const { the, dl } = hzns(pfl, DIST_10KM, HG, GME)
    // Python: the[0]=0.008179, the[1]=0.008154, dl[0]=2860, dl[1]=2880
    expect(the[0]).toBeCloseTo(0.008179, 4)
    expect(the[1]).toBeCloseTo(0.008154, 4)
    expect(dl[0]).toBeCloseTo(2860, 0)
    expect(dl[1]).toBeCloseTo(2880, 0)
  })

  it('short path 1km — matches Python reference', () => {
    const pfl = makePfl(NP_50, XI_1KM, flatElev(100))
    const { the, dl } = hzns(pfl, DIST_1KM, HG, GME)
    // Python: the[0]=-0.02069, the[1]=0.01931, dl={0:1000, 1:1000}
    expect(the[0]).toBeCloseTo(-0.02069, 3)
    expect(the[1]).toBeCloseTo(0.01931, 3)
    expect(dl[0]).toBeCloseTo(1000, 0)
    expect(dl[1]).toBeCloseTo(1000, 0)
  })

  it('mountain ridge — matches Python reference', () => {
    const pfl = makePfl(NP_500, XI_10KM, (_i, frac) => {
      if (Math.abs(frac - 0.6) < 0.05) return 500
      if (frac < 0.6) return 100 + (frac / 0.6) * 400
      return 500 + ((frac - 0.6) / 0.4) * (-400)
    })
    const { the, dl } = hzns(pfl, DIST_10KM, HG, GME)
    // Python: the[0]=0.06348, the[1]=0.10837, dl[0]=5500, dl[1]=3520
    expect(the[0]).toBeCloseTo(0.06348, 3)
    expect(the[1]).toBeCloseTo(0.10837, 3)
    expect(dl[0]).toBeCloseTo(5500, 0)
    expect(dl[1]).toBeCloseTo(3520, 0)
  })

  it('zero distance returns zero horizons', () => {
    const pfl = makePfl(10, 1, flatElev(100))
    const { the, dl } = hzns(pfl, 0, HG, GME)
    expect(the[0]).toBe(0)
    expect(the[1]).toBe(0)
    expect(dl[0]).toBe(0)
    expect(dl[1]).toBe(0)
  })

  it('minimum intervals (np < 2) returns initial values', () => {
    // With only 1 sample, the loop doesn't execute.
    const pfl = new Float64Array(5)
    pfl[0] = 1 // np = 1 interval
    pfl[1] = 100 // spacing
    pfl[2] = 100 // elev
    pfl[3] = 100 // elev
    const { the, dl } = hzns(pfl, 100, HG, GME)
    expect(dl[0]).toBe(100)
    expect(dl[1]).toBe(100)
  })
})

// ---------------------------------------------------------------------------
// dlthx — delta-h terrain irregularity
// ---------------------------------------------------------------------------

describe('dlthx', () => {
  it('flat terrain — delta-h is zero', () => {
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    const dh = dlthx(pfl, 0, DIST_10KM)
    expect(dh).toBeCloseTo(0, 4)
  })

  it('single hill — positive delta-h', () => {
    const pfl = makePfl(NP_500, XI_10KM, gaussianHill(100, 50, 0.5, 0.1))
    const dh = dlthx(pfl, 0, DIST_10KM)
    // Python reference: 128.40
    expect(dh).toBeGreaterThan(0)
    expect(dh).toBeCloseTo(128.40298, 1)
  })

  it('two hills — larger delta-h', () => {
    const pfl = makePfl(NP_500, XI_10KM, (_i, frac) => {
      let elev = 100
      elev += 60 * Math.exp(-((frac - 0.3) ** 2) / (2 * 0.08 ** 2))
      elev += 40 * Math.exp(-((frac - 0.7) ** 2) / (2 * 0.06 ** 2))
      return elev
    })
    const dh = dlthx(pfl, 0, DIST_10KM)
    // Python reference: 143.63
    expect(dh).toBeCloseTo(143.6267, 1)
  })

  it('mountain ridge — high delta-h', () => {
    const pfl = makePfl(NP_500, XI_10KM, (_i, frac) => {
      if (Math.abs(frac - 0.6) < 0.05) return 500
      if (frac < 0.6) return 100 + (frac / 0.6) * 400
      return 500 + ((frac - 0.6) / 0.4) * (-400)
    })
    const dh = dlthx(pfl, 0, DIST_10KM)
    // Python reference: 965.82
    expect(dh).toBeCloseTo(965.8246, 0)
  })

  it('short flat path — delta-h is zero', () => {
    const pfl = makePfl(NP_50, XI_1KM, flatElev(100))
    const dh = dlthx(pfl, 0, DIST_1KM)
    expect(dh).toBeCloseTo(0, 4)
  })

  it('subset with no separation returns zero', () => {
    const pfl = makePfl(NP_500, XI_10KM, flatElev(100))
    // xb - xa < 2 (in terms of grid indices) → returns 0
    const dh = dlthx(pfl, 0, 1)
    expect(dh).toBe(0)
  })
})
